version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-all:
        patterns:
          - "*"               # put every npm update in this group

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      gha-all:
        patterns:
          - "*"               # group every Action bump into one PR
