name: 'Unlock Issues'
description: 'Unlock an issue, to be used on an event.'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
    default: '${{ github.token }}'
  issue-number:
    description: "Issue number. Defaults to context's issue"
    required: false
  owner-name:
    description: "Repository owner's username. Defaults to context's repository owner"
    required: false
  repo-name:
    description: "Repository name. Defaults to context's repository"
    required: false
branding:
  icon: unlock
  color: black
runs:
  using: 'node20'
  main: 'src/unlock.js'
